### ISSUE TITLE
Exception on jekyll serve (Uninitialized constant)

### ISSUE THREAD

**Issue by Andre601** [tzinfo/tzinfo#144]
When setting up the Gemfile did I encounter the following exception during `bundle exec jekyll serve --livereload`:
```shell
jekyll 3.9.2 | Error:  uninitialized constant TZInfo::Timezone

        tz = TZInfo::Timezone.get(timezone)
                   ^^^^^^^^^^
D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/utils/win_tz.rb:16:in `calculate': uninitialized constant TZInfo::Timezone (NameError)

        tz = TZInfo::Timezone.get(timezone)
                   ^^^^^^^^^^
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll.rb:130:in `set_timezone'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll.rb:118:in `block in configuration'
        from <internal:kernel>:90:in `tap'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll.rb:117:in `configuration'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/command.rb:43:in `configuration_from_options'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:89:in `start'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from D:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
        from D:/Ruby31-x64/bin/jekyll:25:in `load'
        from D:/Ruby31-x64/bin/jekyll:25:in `<main>'
```
Could this be due to an incompatible version?

My current gem file:
```gem
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

group :jekyll_plugins do
  gem 'github-pages'
  gem 'jekyll-octicons'
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
end
```

**Comment by Andre601** [comment]
Also, I've tried to use a newer version of Jekyll, in case this was an issue with an outdated version (github-pages ships an old version it seems), but the error remains even with 4.3.1

**Comment by Andre601** [comment]
I've managed to solve this issue after some tinkering...

For anyone else encountering this issue, this Gemfile setup solved it for me:
```gemfile
# frozen_string_literal: true

source "https://rubygems.org"

gem 'wdm', '~> 0.1.1', :install_if => Gem.win_platform?

gem 'webrick'

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem 'tzinfo', '>= 1', '< 3'
  gem 'tzinfo-data'
end

group :jekyll_plugins do
  gem 'github-pages'
  gem 'jekyll-octicons'
end
```

**Comment by arthurcorrell** [comment]
I was getting the same error, also fixed by adding these lines:

```
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem 'tzinfo', '>= 1', '< 3'
  gem 'tzinfo-data'
end

```
